
package InterfasGrafica;

import img.ImgFondo;


public class Users extends javax.swing.JFrame {

    ImgFondo p = new ImgFondo();
    public Users() {
        this.setContentPane(new ImgFondo());
        initComponents();
        this.setTitle("Gestion de usuarios");
        this.setLocationRelativeTo(null);
        this.setSize(450,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_dashboard = new javax.swing.JPanel();
        users_Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        users_txt_User = new javax.swing.JTextField();
        users_txt_Password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        users_opt_AddUser = new javax.swing.JCheckBox();
        users_opt_AddEmployes = new javax.swing.JCheckBox();
        users_opt_ReadOnly = new javax.swing.JCheckBox();
        users_btn_addUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        users_btn_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        user_dashboard.setBackground(new java.awt.Color(102, 0, 255));
        user_dashboard.setMaximumSize(new java.awt.Dimension(600, 800));
        user_dashboard.setMinimumSize(new java.awt.Dimension(300, 450));
        user_dashboard.setName(""); // NOI18N
        user_dashboard.setOpaque(false);
        user_dashboard.setPreferredSize(new java.awt.Dimension(450, 500));

        users_Title.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        users_Title.setForeground(new java.awt.Color(255, 255, 255));
        users_Title.setText("Añadir Usuario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");

        users_txt_User.setText("Ingrese usuario");

        users_txt_Password.setText("Ingrese contraseña");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");

        users_opt_AddUser.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        users_opt_AddUser.setForeground(new java.awt.Color(255, 255, 255));
        users_opt_AddUser.setText("Agregar Usuarios");

        users_opt_AddEmployes.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        users_opt_AddEmployes.setForeground(new java.awt.Color(255, 255, 255));
        users_opt_AddEmployes.setText("Alta de empleados");
        users_opt_AddEmployes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                users_opt_AddEmployesActionPerformed(evt);
            }
        });

        users_opt_ReadOnly.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        users_opt_ReadOnly.setForeground(new java.awt.Color(255, 255, 255));
        users_opt_ReadOnly.setText("Solo lectura");

        users_btn_addUser.setText("Añadir");
        users_btn_addUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        users_btn_addUser.setBorderPainted(false);
        users_btn_addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        users_btn_addUser.setPreferredSize(new java.awt.Dimension(120, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione los permisos del usuario:");

        users_btn_return.setText("Regresar");
        users_btn_return.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        users_btn_return.setBorderPainted(false);
        users_btn_return.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        users_btn_return.setPreferredSize(new java.awt.Dimension(120, 40));
        users_btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                users_btn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout user_dashboardLayout = new javax.swing.GroupLayout(user_dashboard);
        user_dashboard.setLayout(user_dashboardLayout);
        user_dashboardLayout.setHorizontalGroup(
            user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_dashboardLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(users_opt_AddUser)
                    .addComponent(users_opt_AddEmployes)
                    .addGroup(user_dashboardLayout.createSequentialGroup()
                        .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(users_txt_User)
                            .addComponent(users_txt_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(user_dashboardLayout.createSequentialGroup()
                        .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(users_opt_ReadOnly)
                            .addGroup(user_dashboardLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(users_btn_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(users_btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(user_dashboardLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(users_Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_dashboardLayout.setVerticalGroup(
            user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_dashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(users_Title)
                .addGap(30, 30, 30)
                .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(users_txt_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(users_txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(users_opt_AddUser)
                .addGap(18, 18, 18)
                .addComponent(users_opt_AddEmployes)
                .addGap(18, 18, 18)
                .addComponent(users_opt_ReadOnly)
                .addGap(38, 38, 38)
                .addGroup(user_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(users_btn_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users_btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(user_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(user_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void users_opt_AddEmployesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_users_opt_AddEmployesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_users_opt_AddEmployesActionPerformed

    private void users_btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_users_btn_returnActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_users_btn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel user_dashboard;
    private javax.swing.JLabel users_Title;
    private javax.swing.JButton users_btn_addUser;
    private javax.swing.JButton users_btn_return;
    private javax.swing.JCheckBox users_opt_AddEmployes;
    private javax.swing.JCheckBox users_opt_AddUser;
    private javax.swing.JCheckBox users_opt_ReadOnly;
    private javax.swing.JTextField users_txt_Password;
    private javax.swing.JTextField users_txt_User;
    // End of variables declaration//GEN-END:variables
}
